version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/node.Dockerfile
    # command: pm2-runtime start /usr/src/logc/server/index.js -i 2
    command: nodemon /usr/src/logc/server/index.js
    restart: unless-stopped
    volumes:
      - ./:/usr/src/logc:delegated
    depends_on:
      - db
      - redis
    ports:
      - 3001:3000
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logc
    expose:
      - "5432"
  redis:
    image: redis
    restart: unless-stopped
    expose:
      - "6379"
  cms:
    image: strapi/strapi
    restart: unless-stopped
    ports:
      - 1337:1337
